# Generated by Django 3.1.5 on 2021-01-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=1),
        ),
    ]
