# Generated by Django 3.1.5 on 2021-01-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20210126_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
