# Generated by Django 3.1.5 on 2021-01-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210126_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
