# Generated by Django 3.1.5 on 2021-01-26 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20210126_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 19, 57, 9, 947483, tzinfo=utc)),
        ),
    ]
