# Generated by Django 3.1.5 on 2021-01-26 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20210126_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 20, 2, 57, 465180, tzinfo=utc)),
        ),
    ]
