# Generated by Django 3.1.5 on 2021-01-31 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20210128_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 19, 40, 2, 873616, tzinfo=utc)),
        ),
    ]
