# Generated by Django 3.1.5 on 2021-01-20 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=100)),
                ('prize_money', models.IntegerField(blank=True)),
                ('prize_currency', models.CharField(blank=True, max_length=3)),
                ('finished', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_owner', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(through='tournament.Entry', to=settings.AUTH_USER_MODEL)),
                ('winners', models.ManyToManyField(null=True, related_name='tournament_winners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
