# Generated by Django 3.1.5 on 2021-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
