# Generated by Django 3.1.5 on 2021-01-26 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0002_auto_20210126_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='winners',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='tournament_winners', to=settings.AUTH_USER_MODEL),
        ),
    ]
