# Generated by Django 3.1.5 on 2021-01-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20210126_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rounds_number',
            field=models.IntegerField(default=4),
        ),
    ]
