# Generated by Django 3.1.5 on 2021-01-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20210126_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
